### ISSUE TITLE
Unable to start condatis on Mac OS X

### ISSUE THREAD

**Issue by NathanielLegall** [condatis/condatis#1]
I've followed the installation guidance for condatis up until step 6 but I get keep getting this error message. 

Traceback (most recent call last):
  File "./condatis.py", line 26, in <module>
    from mplwidget import MplWidget
  File "/Users/legallmac/Desktop/condatis-master/mplwidget.py", line 25, in <module>
    from PyQt4 import QtCore, QtGui
ImportError: No module named PyQt4

Does anyone know how I can resolve this?

**Comment by NathanielLegall** [comment]
Online version of Condatis software now available here http://wordpress.condatis.org.uk/. Issue closed.
